# Generated by Django 4.2.3 on 2023-10-24 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_academic_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishOptional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishOptionalNumber3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('answer_E', models.TextField()),
                ('answer_F', models.TextField()),
                ('answer_G', models.TextField()),
                ('answer_H', models.TextField()),
                ('answer_I', models.TextField()),
                ('answer_J', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishOptionalNumber4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('topic', models.TextField()),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishOptionalNumber5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('topic', models.TextField()),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('topic', models.TextField()),
                ('answer_A', models.TextField()),
                ('answer_B', models.TextField()),
                ('answer_C', models.TextField()),
                ('answer_D', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('topic', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionalTopicNumber4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.TextField()),
                ('topic', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RemoveField(
            model_name='testpaper',
            name='pid',
        ),
        migrations.RenameField(
            model_name='englishword',
            old_name='meaning',
            new_name='explain',
        ),
        migrations.AddField(
            model_name='englishword',
            name='part_of_speech',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='englishword',
            name='phonetic_symbols',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Testpaper',
        ),
    ]
