# Generated by Django 4.2.3 on 2023-10-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_englishoptional_englishoptionalnumber3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='part_of_speech',
            field=models.TextField(),
        ),
    ]
